### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by mrherickz** [vietaapp/node-mac-sign-in-with-apple#3]
Hello, I have tried to use this lib in my Electron setup but I get this error:

```
TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (webpack:///./node_modules/bindings/bindings.js?:178:16)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:82:48)
    at eval (webpack:///./node_modules/node-mac-sign-in-with-apple/index.js?:1:126)
    at Object../node_modules/node-mac-sign-in-with-apple/index.js
```

Has anyone faced the same and got it fixed?

Electron v11
OSX 11.4

**Comment by jpalumickas** [comment]
Hey, we don't have this error. Do you use https://github.com/electron/electron-rebuild with Electron?

**Comment by mrherickz** [comment]
> Hey, we don't have this error. Do you use https://github.com/electron/electron-rebuild with Electron?

Unfortunately no, I will keep trying here in that case. Thank you!
